project:
  type: website
  preview:
    port: 7211

website:
  title: "MBAts"
  navbar:
    search: false
    pinned: true
    tools:
      - icon: discord
        href: mailto:Krisanat.Anukarnsakulchularp@monash.edu 
    right:
      - href: events.qmd
        text: Events
      # - href: unit_guide.qmd
      #   text: Unit Guide
      - href: course_map.qmd
        text: Course Map

format:
  html:
    theme:
      - default
      - brand
    css: styles.css
    toc: false



