project:
  type: website

website:
  title: "MBAts"
  navbar:
    right:
      - href: events.qmd
        text: Events
      - href: unit_guide.qmd
        text: Unit Guide
      - href: course_map.qmd
        text: Course Map

format:
  html:
    theme:
      - default
      - brand
    css: styles.css
    toc: false



