project:
  type: website
  preview:
    port: 7211

website:
  title: "MBAts"
  navbar:
    search: false
    pinned: true
    tools:
      - icon: discord
        href: https://forms.gle/RYSpnoU1caEBikGf8 
    right:
      - text: Events
        menu: 
          - events.qmd
          - hacky-hour.qmd
      # - href: unit_guide.qmd
      #   text: Unit Guide
      - href: course_map.qmd
        text: Course Map
      - href: people.qmd
        text: The People
      - text: About
        menu: 
          - href: coc.qmd
            text: Code of Conduct

format:
  html:
    theme:
      - default
      - brand
    css: styles.css
    toc: false



